export declare const RAIL_SPACE = 38;
export declare const RAIL_PART_WIDTH = 14;
export declare const ANIMATION_FLOW_COLOR_1 = "royalblue";
export declare const ANIMATION_FLOW_COLOR_2 = "greenyellow";
export declare const CURVED_TURNOUT_ANGLE_DEVIATION = 1;
export declare const GAP_WIDTH = 14;
export declare const GAP_HEIGHT = 4;
export declare const GAP_FILL_COLOR = "red";
export declare const JOINT_WIDTH = 18;
export declare const JOINT_HEIGHT = 8;
export declare const JOINT_HIT_RADIUS = 16;
export declare const JOINT_DETECTION_OPACITY_RATE = 0.5;
export declare const JOINT_FILL_COLORS: string[];
export declare const FEEDER_WIDTH = 26;
export declare const FEEDER_HEIGHT = 26;
export declare const FEEDER_SOCKET_WIDTH = 14;
export declare const FEEDER_SOCKET_HEIGHT = 6;
export declare const FEEDER_SOCKET_HIT_RADIUS = 16;
export declare const FEEDER_SOCKET_DETECTION_OPACITY_RATE = 0.4;
export declare const FEEDER_SOCKET_FILL_COLORS: string[];
export declare const GAP_JOINER_WIDTH = 28;
export declare const GAP_JOINER_HEIGHT = 12;
export declare const GAP_JOINER_SOCKET_HIT_RADIUS = 16;
export declare const GAP_JOINER_SOCKET_DETECTION_OPACITY_RATE = 0.4;
export declare const GAP_JOINER_SOCKET_FILL_COLORS: string[];
